pull_request_rules:
  - name: Automatic merge when required reviews are approved
    conditions:
      - base=master
      - "#approved-reviews-by>=2"
      - status-success=Schema Validation Check
      - status-success=Codacy Static Code Analysis
    actions:
      merge:
        method: merge
