project_id: '369101'
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: websites/**/strings.json
    translation: websites/**/%original_file_name%
    dest: Activities/%original_file_name%
