project_id: "369101"
base_path: .
base_url: "https://api.crowdin.com"
preserve_hierarchy: true
files:
  - source: "websites/*/*/strings.json"
    translation: "websites/*/*/%original_file_name%"
    dest: "Activities/*/*.json"
