blank_issues_enabled: false
contact_links:
  - name: Discord Support
    url: https://discord.premid.app
    about: If you are experiencing issues with your PreMiD, go to our Discord server for help.
  - name: Feature Requests & Presence Requests
    url: https://github.com/PreMiD/Presences/discussions
    about: Suggestions for new presences or feature requests should be on Discussions
