name: Codequality

on:
  schedule:
    - cron: 0 0 */3 * *

jobs:
  Codequality:
    name: Codequality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Deps
        run: yarn
      - name: Run codequality script
        run: yarn codequality
      - name: Install Hub
        run: sudo snap install hub --classic
      - name: Commit any changes
        run: |
          git add .;
          if git diff-index --quiet HEAD --; then
            exit 0;
          else
            hub config --global hub.protocol https;
            hub config --global user.email "${GITHUB_EMAIL}";
            hub config --global user.name "${GITHUB_USER}";
            hub remote set-url origin "https://${GITHUB_TOKEN}:x-oauth-basic@github.com/${GITHUB_REPOSITORY}.git";
            git config --local user.email "${GITHUB_EMAIL}";
            git config --local user.name "${GITHUB_USER}";
            git checkout -b premid-bot/codequality/`date +%F-%H-%M`;
            git commit -sam "refactor: run code quality";
            hub pull-request -p -m "refactor: run code quality on the repo files" -m "*bleep bloop* I ran Codequality on the repo files";
          fi
        env:
          GITHUB_USER: premid-bot
          GITHUB_EMAIL: contact@premid.app
          GITHUB_TOKEN: ${{ secrets.GH_BOT }}