name: Compile and lint
on: [push, pull_request]
jobs:
  compileLint:
    name: Compile and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Compile changed files
        run: yarn compile ${{ github.event_name }} $GITHUB_BASE_REF
      - name: Check Lint
        run: yarn lint:ci
